version: "3"

services:
  hak5c2:
    container_name: hak5c2
    image: lindezagrey/hak5c2
    restart: always
    hostname: localhost
    ports:
      - "2022:2022"
      - "8080:8080"
    volumes:
      - ${PWD}/volumes/hak5c2:/home
    environment:
      db: /home/c2.db

